version: "3.8"
services:
  mysqldb:
    image: mysql:8.0
    container_name: mysql1
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: empldb
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: password
    ports:
       - "3306:3306"
       - "33060:33060"
    volumes:
      - ./db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ecomnet
  ecommerce1:
    image: ecommercee:latest
    container_name: ecommerce_1
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/ecom
      SPRING_DATASOURCE_USERNAME: mysqluser
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    networks:
      - ecomnet
  ecommerceapp:
    image: ng-docker-app:latest
    container_name: ng-docker-app
    ports:
      - "4200:80"
    depends_on:
      - ecommerce1
    networks:
      - ecomnet
networks:
  ecomnet:
    driver: bridge
